export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PROD_SEARCH_TEXT: "SET_PROD_SEARCH_TEXT",
  SELECTED_PRODUCT:"SET_SELECTED_PRODUCT",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_FROM_CART:"REMOVE_FROM_CART",
  ADD_TO_WISHLIST:"ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST:"REMOVE_FROM_WISHLIST",
  // INCREASE_ITEM_QTY:"INCREASE_ITEM_QTY",
  // DECREASE_ITEM_QT:"DECREASE_ITEM_QTY",
  UPDATE_ITEM_QTY:"UPDATE_ITEM_QTY",
  SET_DEPARTMENT:"SET_DEPARTMENT",
  
};
